### ISSUE TITLE
Throws Twig Error On Imported Pages

### ISSUE THREAD

**Issue by BenJohnston429** [paulmassen/grav-plugin-seo#1]
Hi,

I'm in the process of moving my blog from WordPress to Grav and have encountered issues with this plugin on my imported posts. It works fine for newly-created pages, but the imported ones throw up the attached series of issues.

I'm using the latest version of Grav and the Admin plugin with the latest version of this SEO plugin with the Future Imperfect theme (https://github.com/absalomedia/grav-theme-future)

Any help appreciated.

Thanks,

Ben
[errors.txt](https://github.com/paulmassen/grav-plugin-seo/files/1034216/errors.txt)

**Comment by paulmassen** [comment]
Hi and thanks for reporting this. 

It seems like it might be a problem related to your page summary.

If you exported page with wp2grav, it adds the summary delimiter in the exported markdown pages and this summary delimiter might not be present on your newly created pages.
Can you tell me what settings you set in Configuration -> Site -> Summary and give me an example of an exported pages where it causes problem?

Let me know, 

Paul

**Comment by paulmassen** [comment]
I did some major changes today, please try updating the plugin to 0.9.0 and let me know if it still has some error.

**Comment by BenJohnston429** [comment]
That works perfectly, thanks very much for getting back to me.

Thanks,

Ben

**Comment by paulmassen** [comment]
Great! 
Feel free to post other issues, even for small details!
