### ISSUE TITLE
Strange error on latest beta

### ISSUE THREAD

**Issue by JohnMica** [paulmassen/grav-plugin-seo#12]
Seems that in the latest beta # v2.0.0 if the plugin is enabled it gives out an error that it cannot find the class $twitterid in the PHP code.

I appreciate the development of this as I believe it will help make sites more 'social-friendly' as soon as this error is fixed.

i'm on latest Grav v1.3.2 - Admin v1.5.2 in case you were wondering.

![captura de ecran din 2017 09 07 la 21 35 20](https://user-images.githubusercontent.com/7076631/30184099-b8606914-9414-11e7-9f45-58173d6f7b05.png)

**Comment by paulmassen** [comment]
Hello JohnMica and thanks for reporting this.

This is fixed on the develop branch alongside with many other bugs. 
You can try it by downloading the zip from the branch, or wait for the next update, probably today.

Do not hesitate to report any other bug.

Thanks again, 

Paul

**Comment by paulmassen** [comment]
Fixed on https://github.com/paulmassen/grav-plugin-seo/releases/tag/v2.0.2
