### ISSUE TITLE
Twitter SEO tab can't be disabled

### ISSUE THREAD

**Issue by tadesign** [paulmassen/grav-plugin-seo#15]
Hi Paul,

I want to disable the twitter SEO section on a page (possibly re-enabling it in the future) however if I select the Enabled Yes/No button in the twitter tab of the SEO pluggin within the Grav admin, then save the page the button goes back to showing Twitter SEO as Enabled and indeed the source shows the Twitter meta tags in the head area. The Facebook tab disables fine but not Twitter.

![issue-disabling-twitter-seo](https://user-images.githubusercontent.com/4374616/30215930-6157f818-94a9-11e7-868b-e815066ad92d.PNG)

I've tried this locally and on a web server. 

I hope you can help.

Kind Regards
Richard

**Comment by paulmassen** [comment]
hi tadesign, 

Thanks for reporting this. Unfortunately, that's not something I can reproduce. What version of the plugin are you using and what version of Grav and Grav-Admin ?

There is a new release v2.0.3 that fixes a lot of problem (and create some other). Are you using this one? If you are using an old one, be careful before updating as it could break some old installation. So make some backup before

**Comment by tadesign** [comment]
Hi Paul,

The latest version of Grav and the admin panel (released today) and I had the problem with the previous versions too. The version of the plugin I'm using is 1.0.4. Not to worry though, I'm early in development of this site so it won't be a problem to upgrade to the newer version, I'll re-open the issue if it still exists in the newer version.

Many thanks.

Kind Regards
Richard

**Comment by paulmassen** [comment]
you are welcome. 

The main change is that previous version required to include some template provided by the plugin, and to delete some others.  It's not the case anymore, and the plugin should work on most installation out of the box.

Feel free to let me know if you have some problem updating.
