### ISSUE TITLE
Title tag is not present anymore

### ISSUE THREAD

**Issue by DamienBolus** [paulmassen/grav-plugin-seo#23]
Hi, 
Since I updated  to v 2.0.5 (from 1.0.4)  on Grav v1.3.3, the title tag is not inserted anymore on any pages.

I compared both version template, and here is the "missing line" on '/templates/partials/seo_data.html.twig_' : 
`<title>{% if page.header.googletitle is defined and not empty %}{{ page.header.googletitle}}{% else %}{{ page.title }} | {{ site.title }}{% endif %}</title>`

I re-added  the line and now it's working as expected. 
Let me know if you need more info. 
Regards
Damien

**Comment by paulmassen** [comment]
Hello Damien,

On this new version, you don't need to include this template anymore. 
Your base.html.twig just needs to have these two lines:
    <title>{{ page.title }}</title>
    {% include 'partials/metadata.html.twig' %}
and you can now remove the seo_data.html.twig include.

Let me know if if works as expected.

Thanks,

Paul

**Comment by DamienBolus** [comment]
Hi, 
It Works ! as expected. 
Thanks a lot.
Damien
