### ISSUE TITLE
Microdata Does Not show Up

### ISSUE THREAD

**Issue by DanielSokil** [paulmassen/grav-plugin-seo#25]
When I Click On Microdata, nothing shows up, Running latest version of Grav and this Plugin.
![selection_022](https://user-images.githubusercontent.com/24403355/31142900-9f4e9dbc-a849-11e7-9775-5d7909aeada4.png)

**Comment by DanielSokil** [comment]
Never Mind, I figured out it has to be enabled in Settings.

**Comment by paulmassen** [comment]
I keep this open as it reminds me that I should add a text message when none of them are enabled.

**Comment by paulmassen** [comment]
Microdata will now default to 1 instead of disabled
