### ISSUE TITLE
 No "url" field in Organization microdata

### ISSUE THREAD

**Issue by Magalex-2x14** [paulmassen/grav-plugin-seo#29]
![sdata](https://user-images.githubusercontent.com/4982025/31636817-bca5c4a4-b2d4-11e7-9442-fb6e80563f6e.jpg)
"url" field is absent in Organization microdata - google microdata testing tool recognize it as an error...

**Comment by paulmassen** [comment]
Thanks for reporting this.

This field is added in next release all along with a lot of new features, but I'm waiting for some changes on grav assets handling before the release. This week hopefully.

Thanks, 

Paul

**Comment by Magalex-2x14** [comment]
Look forward to! Thank you!
