### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by Sh0velMan** [paulmassen/grav-plugin-seo#3]
Here's the full error text:
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Users/matt/Development/tearaparts-grav/system/src/Grav/Common/Twig/Twig.php on line 222

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Users/matt/Development/tearaparts-grav/vendor/filp/whoops/src/Whoops/Run.php on line 353
```

Additionally, I get an "Invalid Security Token" error when I try to save a page.

I have reinstalled using GPM, no change. If I disable the plugin, I can once again save pages. 

This just started after the last update. 

Let me know what other info you require! Thanks!
<img width="1508" alt="seo_plugin_error" src="https://cloud.githubusercontent.com/assets/20350969/26762718/7dfef112-490c-11e7-8de1-941e1d0db104.png">

<img width="1336" alt="seo_plugin_page" src="https://cloud.githubusercontent.com/assets/20350969/26762698/0bdda5a6-490c-11e7-9e6a-94838e230127.png">

**Comment by paulmassen** [comment]
Thanks for reporting this.

This might be a server config error. It looks like you are on local. Can you check the value of memory limit in your php.ini and try to change with 
```
memory_limit = 256M
```

Don't forget to restart apache

Alternatively, try clearing your cache and let me know if it works.

**Comment by Sh0velMan** [comment]
Hi there, I've cleared cache several times, reloaded the plugin from GPM after removing it with an 'rm -rf', no change. I will triple check, but I'm seeing this on the production server as well, I didn't do a lot of testing up there because I don't make a habit of such things, but I'll confirm. The only change in environment is the update you pushed out three days ago, however. 

Your time is appreciated! I'll do some more checking and report back.

**Comment by paulmassen** [comment]
ah, I have an idea, but first: 

- do you use summary on your page?

- does it happen on other tabs if twitter title and facebook title is not set? 

- does it disappear if you manually set a title for google?

**Comment by Sh0velMan** [comment]
It happens if I do nothing at all related to SEO in any way.

If I create a new page the memory error is already showing, if I then click 'Save' (to actually commit the page to disk), I get the Invalid Security Token error.

Basically with the plugin enabled, I can't create content.

**Comment by paulmassen** [comment]
I guess you already took a look at this: https://learn.getgrav.org/troubleshooting/common-problems#invalid-security-token

I will investigate this further tomorrow but its very weird that turning it off seems to fix your problem. 

One last thing : does removing the config yaml in user/config/seo.yaml change something?

**Comment by Sh0velMan** [comment]
When I remove `user/config/plugins/seo.yaml ` I no longer get the error about memory (and on the prod server, which is apache, a hard 500 error) but I still get the token error. 

If I disable the plugin, no token error.

**Comment by paulmassen** [comment]
ok thats a first step, and thats why it did not change even after uninstall/reinstall at first.

**Comment by Sh0velMan** [comment]
I wish I could provide more info. There doesn't seem to be a definitive way to get useful debug logging from Grav. There's rarely anything useful until you cause a real exception and resulting stack trace.

**Comment by paulmassen** [comment]
Any update on this?

**Comment by Sh0velMan** [comment]
No, I was going to ask you the same thing? 

Still does not work in either the dev (nginx on MacOS Sierra) or prod (Apache on Centos) environments.

**Comment by paulmassen** [comment]
Hmm, at this point, I don't know what to do. 
Could you zip me your site folder? My email is in the blueprints

**Comment by lukevhf** [comment]
Sometimes i have the same problem only with new plugin and when i first try to use but only when i clear cronology in web browser or file 
In  manual mode in cache/grav.. i resolve a problem...i forget but only with no test release...
I don't know why but when i change manual and i don't save in admin plugin nothing works...
I open page, clear cache save and restart

**Comment by Sh0velMan** [comment]
So this just.. stopped happening.

I can't explain why, but seems to be resolved now, in both environments.

**Comment by paulmassen** [comment]
hmm strange, 

let me know if it happens again.

**Comment by paulmassen** [comment]
Hi Sh0velMan 

I updatted the plugin with new features, and now it works on any Grav install, without editing any template.

If you update, make sure to restore the templates that had to be removed for the previous version of the plugin to works.

Let me know how it goes and if you have some problem.

The v2.0.4 is available on the GPM by enabling testing: true in the configuration.
