### ISSUE TITLE
Many duplicate field in blueprint

### ISSUE THREAD

**Issue by jimblue** [paulmassen/grav-plugin-seo#31]
Hi @paulmassen !

You should use a yaml linter... Your Blueprint is full of duplicates:

https://github.com/paulmassen/grav-plugin-seo/blob/840d001d2342e71f3d1c9a4ac5985719ebf71c49/blueprints/seo.yaml#L156

https://github.com/paulmassen/grav-plugin-seo/blob/840d001d2342e71f3d1c9a4ac5985719ebf71c49/blueprints/seo.yaml#L211

https://github.com/paulmassen/grav-plugin-seo/blob/840d001d2342e71f3d1c9a4ac5985719ebf71c49/blueprints/seo.yaml#L253

https://github.com/paulmassen/grav-plugin-seo/blob/840d001d2342e71f3d1c9a4ac5985719ebf71c49/blueprints/seo.yaml#L262

https://github.com/paulmassen/grav-plugin-seo/blob/840d001d2342e71f3d1c9a4ac5985719ebf71c49/blueprints/seo.yaml#L347

https://github.com/paulmassen/grav-plugin-seo/blob/840d001d2342e71f3d1c9a4ac5985719ebf71c49/blueprints/seo.yaml#L393

https://github.com/paulmassen/grav-plugin-seo/blob/840d001d2342e71f3d1c9a4ac5985719ebf71c49/blueprints/seo.yaml#L462

https://github.com/paulmassen/grav-plugin-seo/blob/840d001d2342e71f3d1c9a4ac5985719ebf71c49/blueprints/seo.yaml#L503

https://github.com/paulmassen/grav-plugin-seo/blob/840d001d2342e71f3d1c9a4ac5985719ebf71c49/blueprints/seo.yaml#L573

**Comment by paulmassen** [comment]
thanks you jim, that is just a merge that went wrong. it should still work afaik but will be removed in next release

**Comment by paulmassen** [comment]
Removed in https://github.com/paulmassen/grav-plugin-seo/commit/4e582e0b16238ae64a7ac19fbe49f42233a301ea
