### ISSUE TITLE
Enhanced Microdata

### ISSUE THREAD

**Issue by s0kil** [paulmassen/grav-plugin-seo#37]
Could You please add support for this microdata?

```
"openingHours": [
"Mon-Fri 09:00-18:00", "Saturday 09:00-15:00"],
"aggregateRating":{
"@type":"AggregateRating",
"ratingValue":"5.0",
"reviewCount":"2"},
"priceRange":"2",
"paymentAccepted":"Visa, Master Card, Discover, Amex"
"email":"",
```

**Comment by DanielSokil** [comment]
All together looks like this,

```
<script type="application/ld+json"> {
"@context" : "http://schema.org",
"@type" : "",
"address" : {
"@type": "PostalAddress",
"addressLocality": "",
"addressRegion": "",
"postalCode": "",
"streetAddress": "" },
"name":"",
"url":"",
"email":"",
"image": "",
"telephone":"",
"openingHours": [
"Mon-Fri 09:00-18:00", "Saturday 09:00-15:00"],
"aggregateRating":{
"@type":"AggregateRating",
"ratingValue":"5.0",
"reviewCount":"2"},
"priceRange":"2",
"paymentAccepted":"Visa, Master Card, Discover, Amex"
} </script>
```

**Comment by paulmassen** [comment]
sure, will add it tomorrow

Cheers

**Comment by paulmassen** [comment]
Here it is: https://github.com/paulmassen/grav-plugin-seo/commit/9b093f3273555bc8ccac883c96a3dd3bc48aeaad

Would be great if you could download the zip from master and let me know how it works.

**Comment by DanielSokil** [comment]
@paulmassen  Works great Will let you know if any bugs.

**Comment by paulmassen** [comment]
great and let me know if it validates correctly too

**Comment by DanielSokil** [comment]
Is there a way to update the type `Organization`. Ex to `GeneralContractor`.
```
<script type="application/ld+json">
--
  | {
  | "@context": "http://schema.org",
  | "@type": "Organization",
  | "name": "",
  | "address": {
  | "@type": "PostalAddress"
  | }
  | }
  | </script>
```

**Comment by paulmassen** [comment]
Sorry for the delay. It could be a good idea indeed, but I think I will instead add it to the future localbusiness microdata instead.

Am still not sure about this, as I don't think it provide anything more than organization, so maybe I will instead use organization with a select box to use it as a localbusiness instead.
I will take a look and let you know, but don't hesitate to share your finds.
