### ISSUE TITLE
Google has made search results snippets longer

### ISSUE THREAD

**Issue by xetorixik** [paulmassen/grav-plugin-seo#38]
In the past it showed up to ~160 characters, now it can be much, much longer.
Snippets can now be up to 320 characters or even longer in some rare cases.

Please expand the 'Characters left: 140' in the Grav-plugin-seo.

Source: 
1. https://yoast.com/meta-description-length/
2. http://www.seoblog.com/2017/12/meta-description-320-characters/
3. https://moz.com/blog/googles-longer-snippets

**Comment by paulmassen** [comment]
Description is now 320 character long. Thanks!
