### ISSUE TITLE
Insert plugin in TWIG

### ISSUE THREAD

**Issue by skazhikadyadya** [paulmassen/grav-plugin-seo#39]
Hi, thank you for nice plugin. How I can insert it to my custom twig?

**Comment by paulmassen** [comment]
what do you mean exactly ? are toi using a custom made theme?

**Comment by skazhikadyadya** [comment]
Yes, I try to create my custom theme.

**Comment by paulmassen** [comment]
I will document how to add the plugin to a custom theme. Thanks

**Comment by paulmassen** [comment]
Documented here: https://github.com/paulmassen/grav-plugin-seo/commit/031c819ba9333b055fe29465971f6b99cd01f38a
