### ISSUE TITLE
Url on twitter and facebook

### ISSUE THREAD

**Issue by lukevhf** [paulmassen/grav-plugin-seo#4]
Sorry but i'm new of this beautiful grav cms..
i try to use for one site this plugin but i don't find if is possible write the url of pages for fb or twitter..
if is possible and i don't find please tell me how i put...
Thanks and sorry for my english

**Comment by paulmassen** [comment]
hi! For Facebook, the url is written automatically but you are right that I need to add it fir twitter.

Update incoming!

**Comment by lukevhf** [comment]
Thanks...
For me now is very googd job and i think that don't need more update...
Have fb, have twitter and have microdata(very important for seo)..
Only i think that if is possible to write url for fb or twitter in tab is more userfriendly and when someone write appears in preview...
thanks for your good works..
thanks

**Comment by paulmassen** [comment]
https://github.com/paulmassen/grav-plugin-seo/commit/9227365190b1d30d0b174b23cbbcbf4df91a2ef7

**Comment by lukevhf** [comment]
Thanks for new release that i try later...
I think that is better for user customize url because:
1)is beautiful if in preview i read my Facebook name like google and if is possible write this name appear....
2) i see when i read a code in html that don't appear url but only local url and others important tags like url don't appear like image if image is in fb or Twitter and i don't have in project...
If you make possible for user customize image, url and others tags for me this project is awesome.
3) if you want, because seo is very important on web i write you tags that you haven't use for be this project more good than now...
I think that this project is more good specially because you start to make this but is possibile to improve.
Thanks for your work and sorry for my bad italian/english....

**Comment by paulmassen** [comment]
Closing this as the new releases fixes most of this problem
