### ISSUE TITLE
Problem to other Plugin

### ISSUE THREAD

**Issue by dadannurman** [paulmassen/grav-plugin-seo#41]
Problem is on "SEO v2.1.7", before this version no problem.

I use "lightslider plugin",
when "SEO Plugin" disable, "lightslider plugin" is working,
but if "SEO Plugin" is enable, "lightslider plugin" is error.

![seo](https://user-images.githubusercontent.com/28327817/34594496-03adcc7a-f204-11e7-90ba-7e877845f1f0.PNG)

**Comment by paulmassen** [comment]
Does it happen on every page? If no, can you post the content of your page.md file?

**Comment by dadannurman** [comment]
this is not on the outside page, but on the page admin when editing a page that uses the plugin (lightslider)

**Comment by dadannurman** [comment]
this page opens when seo plugin is off,

![a](https://user-images.githubusercontent.com/28327817/34636606-24ee349a-f2d8-11e7-874a-23ff2266ccd2.PNG)

but when it is on, error

![a](https://user-images.githubusercontent.com/28327817/34594496-03adcc7a-f204-11e7-90ba-7e877845f1f0.PNG)

**Comment by paulmassen** [comment]
Hi, 

I managed to replicate the error. This is because the "process twig" is enabled. Usually, adding a slider is done through modular, that's why I never encountered this problem.

I will think about this some more, but for now, moving the include out of the first 300 character should make it work

I will keep you updated.

**Comment by dadannurman** [comment]
![seoo](https://user-images.githubusercontent.com/28327817/34760282-bbdbe230-f611-11e7-9eab-3bfe63edc2ea.PNG)

its still error,

other pages "process twig" is enabled but no error found. only on the installed "lightslider" plugin.

**Comment by paulmassen** [comment]
This should be fixed in latest release. Can you give it a try?

Thanks!
https://github.com/paulmassen/grav-plugin-seo/releases/tag/v2.2.0
