### ISSUE TITLE
Missing Founder field with Organization will crash the site

### ISSUE THREAD

**Issue by CSixtyFour** [paulmassen/grav-plugin-seo#42]
Hi
I've used the Organization Microdata section some of my pages - all fine. I left off the founder field on one and it crashed that page.

![image](https://user-images.githubusercontent.com/5107817/34645381-af816c10-f343-11e7-99c8-e47b16d06f90.png)

**Comment by paulmassen** [comment]
Thank you for reporting this, 

It should be fixed with the latest update. Can you confirm?

**Comment by CSixtyFour** [comment]
👍 
Added, deleted, readded the founder field without any errors.
Thanks a lot

**Comment by paulmassen** [comment]
great! Im  closing this issue

**Comment by CSixtyFour** [comment]
Actually spoke too soon :(
The SEO fields are working fine but just navigating onto another page gives an error. Most of my pages are modular if that's relevant

![image](https://user-images.githubusercontent.com/5107817/34689133-618d1a08-f4ac-11e7-92d2-c405bca0c714.png)

**Comment by CSixtyFour** [comment]
I think it might be a typo in seo.php
This
`if (0 === strpos($newtype, $excludetype or 0 === strpos($newtype, 'default'))) {`
Should be
`if (0 === strpos($newtype, $excludetype) or 0 === strpos($newtype, 'default')) {`

**Comment by paulmassen** [comment]
Many thanks for finding this. This was made for a future feature, for users who would like to disable the seo tab on some pages. I did not see I committed that.
Seo tab should not appear on modular pages, so the problem should have disappeared now.
Good catch!
