### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by DanielSokil** [paulmassen/grav-plugin-seo#43]
Where could I change the default values of the plugin to "false", So when I make a new page, Facebook and Twitter are automatically set to "false".

**Comment by paulmassen** [comment]
it would be an enhancement indeed. will add it for next update

**Comment by paulmassen** [comment]
Available in latest test release, please tell me if it works correctly if you have time.

Thanks!
https://github.com/paulmassen/grav-plugin-seo/releases/tag/v2.2.0
