### ISSUE TITLE
can't change SEO datePublished & dateModified from admin

### ISSUE THREAD

**Issue by STnetwork** [paulmassen/grav-plugin-seo#45]
Hi,

Is it normal that I can't change datePublished & dateModified in article metadata from admin ?

![image](https://user-images.githubusercontent.com/26366663/35319149-d89b52d4-00de-11e8-923f-8642595b1241.png)

**Comment by paulmassen** [comment]
oh, definitely no.

Will investigate. thanks!

**Comment by STnetwork** [comment]
Ok, I wait your news

**Comment by paulmassen** [comment]
Fixed https://github.com/paulmassen/grav-plugin-seo/commit/35201f4dc99498f137f4d10276b08a4b74a384cb

I will release a new version later today.

Thanks!
