### ISSUE TITLE
[Suggestion] json-ld manual input field

### ISSUE THREAD

**Issue by robrechtme** [paulmassen/grav-plugin-seo#46]
First of all, love the plugin! Can you please provide a manual input method where I can paste json code? Since the json-ld definitions are evolving quickly it would be a great alternative for users with a bit of experience.

**Comment by paulmassen** [comment]
It's a good idea indeed. 

I will have to think about how to do that, as it can be useful sometimes.

For other types, I am also creating these days a json-builder with the new grav multilevel field.

Will let you know once it works.

**Comment by paulmassen** [comment]
I'm quite late on this, but this feature was added to the latest testing release.
Let me know if it works as you would like it to.
