### ISSUE TITLE
If I use plugin.....

### ISSUE THREAD

**Issue by lukevhf** [paulmassen/grav-plugin-seo#5]
If i use plugin metadata in grav don't work, f i write manual metadata without admin plugin appear error on page where i write....

**Comment by paulmassen** [comment]
hmm, do you have a screenshot of the error? 

What version did you use?

**Comment by lukevhf** [comment]
I use test release, ultimate but now i try with stable release of grav and plug in....
Problem is :When i use plugin seo and i use meta data in admin plugin only plugin works and no metadata....
What if put in plugin others tags for seo?

**Comment by paulmassen** [comment]
As for now, the plugin does not generate the metadata tags, as it is most of the time made directly by including the antimatter template.
https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/metadata.html.twig
Are you sure you are actually including this metadata.html.twig in the head?

**Comment by lukevhf** [comment]
yes include metadata...
i find solution, i write tags and later i install and use your plugin and always works....
thanks
