### ISSUE TITLE
Google title overwriting page title - could it be optional?

### ISSUE THREAD

**Issue by vhelga** [paulmassen/grav-plugin-seo#55]
Lines 176-178 of seo.php are overwriting page title with googletitle. Could it be optional? Thank you.

        if (isset($page->header()->googletitle)) {
            $page->header()->title = $page->header()->googletitle;
        };

**Comment by paulmassen** [comment]
Hi,

Actually, google use the value between <title> and </title>, so there is no way to "tell" google which title it should use without replacing this value...

**Comment by vhelga** [comment]
Understood, sorry for bothering then. 

Thank you for the plugin, it makes a brilliant job, and is very easy to handle for clients.

**Comment by paulmassen** [comment]
You are very welcome, dont hesitate to let me know would you have other questions.
