### ISSUE TITLE
Weird multilang issue

### ISSUE THREAD

**Issue by drnasin** [paulmassen/grav-plugin-seo#64]
Hi Paul. sorry to bother so much but as you see I use the plugin a LOT :)
I noticed one issue when using facebook sharing debugger. I have my homepage in 2 languages. Main one is slovenian and secondary is croatian (hr tag). When I scrape the croatian homepage, although I have all the tags in croatian it wll be slovenian ones that will get picked up. So i went debugging and saw that for some reason on my homepage/hr og:url is just homepage. Because of that FB thinks /hr is canonical and just shows original og data (for homepage not homepage/hr)...any ideas?

Example: on https://drnasin.com/hr generated og:url is https://drnasin.com (actually it's gonna be HTTP beucause of the current bug in Grav but that's another issue that's currently being resolved)

**Comment by paulmassen** [comment]
I merged @CSixtyFour fix, can you give it a try by reinstalling the plugin manually @drnasin ? 

Backup before, just in case!

**Comment by drnasin** [comment]
Funny enough I already had that file open and cursor was on that exactly same line...lol...
Thank you @CSixtyFour and @paulmassen .

Fix is working!
