### ISSUE TITLE
Adding Currencies

### ISSUE THREAD

**Issue by thekenshow** [paulmassen/grav-plugin-seo#68]
Looking to add a new currency (CAD) to the short list that comes with the SEO plugin. Is there a way to extend `user/plugins/seo/blueprints/seo.yaml`? I tried `user/blueprints/pages/seo.yaml` as suggested on https://learn.getgrav.org/forms/blueprints/example-page-blueprint but it had no effect. Or would I need to create a plugin to get at this list?

**Comment by paulmassen** [comment]
Hi,  

You can add your own currency at the following line:
https://github.com/paulmassen/grav-plugin-seo/blob/master/blueprints/seo.yaml#L253

I think I will replace this select field with a text field instead, in order to allow all currencies.
