### ISSUE TITLE
Schema metadata stopped working altogether

### ISSUE THREAD

**Issue by MelleNi** [paulmassen/grav-plugin-seo#69]
I was using this for the schema metadata, but it stopped working out of nowhere. I tried updating, but to no avail.

Twitter, open graph and title/description function perfectly. It's just the schema that doesn't work anymore.

**Comment by MelleNi** [comment]
At the moment I am using the latest versions of Grav, Admin and SEO. 

Earlier today I noticed the problem, and I hadn't yet updated. So I updated, and tried to republish and refresh pages, but nothing.

**Comment by paulmassen** [comment]
Did you change theme? do you use an official one?
Usually, the only thing you have to check is to make sure your theme has somewhere the {{ assets.js() }} in your base template. Is that the case?

**Comment by MelleNi** [comment]
Ah, that's it, that was absolutely dumb of me. I stripped down and removed all javascript from my theme a while back, and I didn't think of keeping the assets.js() there.
***
On a side note, I tried to add the schema for a visual artwork, and I managed to do something that functioned, but it wasn't anything near decent. 

So I am trying to add this:
{
    "@context": "http://schema.org",
    "@type": "visualArtwork",
    "name": "Untitled",
    "description": "This is an artwork.",
    "artform": "form",
    "artMedium": "medium 1",
    "artMedium": "medium 2",  (ideally you should be able to add infinite media)
    "dateCreated": 0000,
    "image": "/route/to/image.jpg",
    "creator": {
        "@type": "Person",
        "name": "Firstname Surname",
        "sameAs": "https://example.com"
    }
}

**Comment by paulmassen** [comment]
Ah, for specific microdata, you can add them manually with the New version of the plugin

**Comment by MelleNi** [comment]
Thanks, just read about it in an old issue. Cheers
