### ISSUE TITLE
Event Offer Currency Not Appearing

### ISSUE THREAD

**Issue by thekenshow** [paulmassen/grav-plugin-seo#72]
When I validate my Event Microdata, Google flags the following even though my Event Offer Currency  field has "CAD":

> priceCurrency - The priceCurrency field is recommended. Please provide a value if available.

I confirmed this in my rendered page:

```
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Event",
    "name": "Working Mindfully with Anxiety",
    "location": {
        "@type": "Place",
        "name": "Online/Zoom",
        "address": {
            "@type": "PostalAddress"
        }
    },
    "description": "This course explores ways we can use mindfulness and meditation to help with anxiety in everyday life.",
    "offers": {
        "@type": "Offer",
        "price": "95",
        "url": "https://communitymeditation.net/courses-and-events/mississauga/working-mindfully-with-anxiety"
    },
    "startDate": "2019-02-07T19:00:00+00:00",
    "endDate": "2019-02-21T19:00:00+00:00"
}
</script>
```
Screen shot shows Google's validation:

![screen shot 2018-11-28 at 8 48 57 am](https://user-images.githubusercontent.com/998832/49156354-2e21bf00-f2eb-11e8-8039-4523a7591973.png)

**Comment by paulmassen** [comment]
Good catch, should be fixed here: https://github.com/paulmassen/grav-plugin-seo/commit/b9876db1353b4aaf29685cc0e59df808862d97d2

Can you confirm?
