### ISSUE TITLE
Can't add Facebook image

### ISSUE THREAD

**Issue by antonijap** [paulmassen/grav-plugin-seo#8]
Title says it all. Plugin works nicely except adding images. Dropdown is unresponsive and if I manualy write img url, it dissapears.

**Comment by paulmassen** [comment]
Hmm, it's weird because it's just a filepicker field, does it happen on all installation? 

I will look into it.

**Comment by antonijap** [comment]
Oh sorry, my mistake. I am new to Grav so I didn't figure I have to upload a picture into content and then come to SEO > Facebook to actually select it.

**Comment by paulmassen** [comment]
ahh, yes, indeed. 
I will change this field for the 'mediapicker' field in order for users to be able to upload some images or select already uploaded ones.
