### ISSUE TITLE
Product Microdata causes Undefined variable: offer error

### ISSUE THREAD

**Issue by 01Kuzma** [paulmassen/grav-plugin-seo#85]
Hi!
It doesn't matter if I fill all the data into 'Product Microdata' card I always receive the same error:
`Undefined variable: offer`

Grav v1.6.26
SEO plugin v2.3.5

**Comment by paulmassen** [comment]
Hi, sorry I'm late, 

I see that you closed the issue, did you find the problem?

**Comment by 01Kuzma** [comment]
Hello!
Yes, it was my fault, because I haven't observed the `add offer` tab. It was empty and caused the error.
But, some fields are missing, because `schema` was updated some time ago. Like these ones:

1. priceValidUntil
2. url
3. sku
4. review
5. globalID

Will it be updated?

Thank you!
