### ISSUE TITLE
Choosing Facebook and Twitter Image Path

### ISSUE THREAD

**Issue by carlu93** [paulmassen/grav-plugin-seo#9]
Hi,

first of all thanks a lot for this awesome plugin. Been searching for an all-in-one SEO Solution for grav for quite some time.
One thing that might help, in my case, would be to customize the image path for facebook and twitter.

For example sometimes I only use one "images" folder inside the theme directory, so i have all my pictures in one place.
Maybe this could be set through the plugin settings. Let me know if this might be easily to implement.
And again thanks a lot! :)

**Comment by paulmassen** [comment]
Hi carlu93,

This is a good idea indeed. I will replace this field with the mediapicker field. that will allows user to pick an image no matter where its location on the grav install.

Stay tuned for the update!

Thanks,

Paul

**Comment by carlu93** [comment]
Hi @paulmassen,

great! Thanks a ton. Looking forward for the update.

Greetings,

Carsten

**Comment by paulmassen** [comment]
added in v2.0.0
